packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"
  - "docs"
  # - "packages/db"
  # - "packages/shared"
  # - "packages/shared-react"
  # - "packages/trpc"
  # - "apps/mobile"
  # - "tooling/eslint"
  # - "tooling/prettier"
  # - "tooling/tailwind"
  # - "tooling/typescript"

overrides:
  "@babel/preset-env": "7.26.9"
  "@swc/core": "1.4.2"
  "@swc/types": "0.1.5"
  "@napi-rs/canvas": "0.1.68"
  "lib0": "0.2.98"
